CREATE SEQUENCE location_state_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE the_partment_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE municipality_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE;
CREATE SEQUENCE terminal_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE;
CREATE SEQUENCE arrival_department_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE;
CREATE SEQUENCE departure_department_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE;
CREATE SEQUENCE travel_id_seq INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE bill_tecno_id_seq INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE state_transport_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE brand_transport_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE state_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE service_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE fuel_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE transport_type_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;
CREATE SEQUENCE employee_box_office_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE type_contract_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE;
CREATE SEQUENCE contract_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE employee_state_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE document_type_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE employee_driver_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE box_office_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE client_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE sale_state_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE sale_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE ticket_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE inventory_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE inventory_state_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE workshift_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
CREATE SEQUENCE the_employee_id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;


CREATE INDEX travel_departure_date_idx ON TRAVEL(DEPARTURE_DATE);
CREATE INDEX travel_arrival_date_idx ON TRAVEL(ARRIVAL_DATE);
CREATE INDEX employee_name_idx ON THE_EMPLOYEE (NAME);
CREATE INDEX sale_date_idx ON SALE(DATE_SALE);
CREATE INDEX client_name_idx ON CLIENT(NAME_USER);


CREATE SYNONYM department_trs FOR THE_DEPARTMENT;
CREATE SYNONYM employee_trs FOR THE_EMPLOYEE;
CREATE SYNONYM ticket_clerk FOR EMPLOYEE_BOX_OFFICE;


/*DROP SEQUENCE location_state_id_seq;
DROP SEQUENCE the_partment_id_seq;
DROP SEQUENCE municipality_id_seq;
DROP SEQUENCE terminal_id_seq;
DROP SEQUENCE arrival_department_id_seq;
DROP SEQUENCE departure_department_id_seq;
DROP SEQUENCE travel_id_seq;
DROP SEQUENCE bill_tecno_id_seq;
DROP SEQUENCE state_transport_id_seq;
DROP SEQUENCE brand_transport_id_seq;
DROP SEQUENCE state_id_seq;
DROP SEQUENCE service_id_seq;
DROP SEQUENCE fuel_id_seq;
DROP SEQUENCE transport_type_id_seq;
DROP SEQUENCE employee_box_office_id_seq;
DROP SEQUENCE type_contract_id_seq;
DROP SEQUENCE contract_id_seq;
DROP SEQUENCE employee_state_id_seq;
DROP SEQUENCE document_type_id_seq;
DROP SEQUENCE employee_driver_id_seq;
DROP SEQUENCE box_office_id_seq;
DROP SEQUENCE client_id_seq;
DROP SEQUENCE sale_state_id_seq;
DROP SEQUENCE sale_id_seq;
DROP SEQUENCE ticket_id_seq;
DROP SEQUENCE inventory_id_seq;
DROP SEQUENCE inventory_state_id_seq;
DROP SEQUENCE workshift_id_seq;
DROP SEQUENCE the_employee_id_seq;


DROP INDEX travel_departure_date_idx;
DROP INDEX travel_arrival_date_idx;
DROP INDEX employee_name_idx;
DROP INDEX sale_date_idx;
DROP INDEX client_name_idx;


DROP SYNONYM department_trs;
DROP SYNONYM employee_trs;
DROP SYNONYM ticket_clerk;*/